version: 2

project_name: s3lo-operator

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/s3lo-proxy
    binary: s3lo-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}"
      - "ghcr.io/oufinx/s3lo-operator:latest"
    dockerfile: Dockerfile
    goarch: amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: OuFinx
    name: s3lo-operator
