version: 2

project_name: s3lo-operator

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/s3lo-proxy
    binary: s3lo-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

  - image_templates:
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/oufinx/s3lo-operator:{{ .Version }}"
    image_templates:
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}-amd64"
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}-arm64"
  - name_template: "ghcr.io/oufinx/s3lo-operator:latest"
    image_templates:
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}-amd64"
      - "ghcr.io/oufinx/s3lo-operator:{{ .Version }}-arm64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: OuFinx
    name: s3lo-operator
