image:
  repository: ghcr.io/oufinx/s3lo-operator
  tag: "0.0.2"
  pullPolicy: IfNotPresent

proxy:
  port: 5732

serviceAccount:
  create: true
  name: s3lo-proxy
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector:
  kubernetes.io/hostname: ip-172-40-11-197.eu-central-1.compute.internal
tolerations: []
