image:
  repository: ghcr.io/oufinx/s3lo-operator
  tag: "1.1.0"
  pullPolicy: IfNotPresent

proxy:
  port: 5732
  presignTTL: "1h"

signing:
  enabled: false
  keyRef: ""       # awskms:// ARN, gcpkms:// URL, or mounted file path
  keySecret:
    name: ""       # name of an existing K8s Secret holding the public key
    key: "key.pub" # key name within that secret

serviceAccount:
  create: true
  name: s3lo-proxy
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}
tolerations: []
